name: Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-20.04

    steps:
    - uses: appleboy/ssh-action@v0.1.2
      name: Deploy App
      with:
        host: ${{secrets.SSH_HOST}} # server ip address
        key: ${{secrets.SSH_KEY}}
        username: ${{ secrets.SSH_USERNAME}}
        
        script: |
          cd /var/www/html/CarlosBojorquezCV
          git pull
